DormService/DormService.sln, DormService/Services/Canteen/Canteen.API/Canteen.API.csproj, DormService/Services/Canteen/Canteen.API/Canteen.API.http, DormService/Services/Canteen/Canteen.API/Program.cs, DormService/Services/Canteen/Canteen.API/Properties/launchSettings.json, DormService/Services/Canteen/Canteen.API/appsettings.Development.json, DormService/Services/Canteen/Canteen.API/appsettings.json
- Initialize Canteen service
- Install necessary packages
=> feat: NA Canteen Service - initialize canteen service

DormService/Services/Laundry/Laundry.csproj, DormService/Services/Laundry/Laundry.http, DormService/Services/Laundry/Program.cs, DormService/Services/Laundry/Properties/launchSettings.json, DormService/Services/Laundry/appsettings.Development.json, DormService/Services/Laundry/appsettings.json
=> Add laundry service structure

DormService/Services/Laundry/Dockerfile, DormService/docker-compose.override.yml, DormService/docker-compose.yml
Implements: #23 and adds docker support for laundry service
=> Add docker support for laundry service

DormService/Services/Payment/Payment.API/Entities/DebtType.cs, DormService/Services/Payment/Payment.API/Entities/Debts.cs
Add two new classes: Debts and DebtType
=> Add classes for Debts

DormService/Services/Canteen/Canteen.API/Canteen.API.csproj, DormService/Services/Canteen/Canteen.API/OrderMealsInfo/Controllers/OrderMealsController.cs, DormService/Services/Canteen/Canteen.API/OrderMealsInfo/Entities/OrderMeals.cs, DormService/Services/Canteen/Canteen.API/OrderMealsInfo/Entities/OrderMealsItem.cs, DormService/Services/Canteen/Canteen.API/OrderMealsInfo/Repositories/IOrderMealsRepository.cs, DormService/Services/Canteen/Canteen.API/OrderMealsInfo/Repositories/OrderMealsRepository.cs, DormService/Services/Canteen/Canteen.API/Program.cs, DormService/Services/Canteen/Canteen.API/UserMealsInfo/Contorllers/UserMealsController.cs, DormService/Services/Canteen/Canteen.API/UserMealsInfo/Data/IUserMealsContext.cs, DormService/Services/Canteen/Canteen.API/UserMealsInfo/Data/UserMealsContext.cs, DormService/Services/Canteen/Canteen.API/UserMealsInfo/Data/UserMealsContextSeed.cs, DormService/Services/Canteen/Canteen.API/UserMealsInfo/Entities/UserMeals.cs, DormService/Services/Canteen/Canteen.API/UserMealsInfo/Repositories/IUserMealsRepository.cs, DormService/Services/Canteen/Canteen.API/UserMealsInfo/Repositories/UserMealsRepository.cs, DormService/Services/Canteen/Canteen.API/appsettings.Development.json, DormService/docker-compose.override.yml, DormService/docker-compose.yml
- Added `UserMealsInfo` for storing information about payed meals
- Updated `docker` settings for MongoDB
=> feat: Canteen - Add MongoDB to Canteen service

DormService/Services/Laundry/Laundry.API/Controllers/WashingMachineController.cs, DormService/Services/Laundry/Laundry.API/Data/WashingMachineContext.cs
=> Fix missing context assignment

DormService/Services/Payment/Payment.API/Controllers/DebtsController.cs, DormService/Services/Payment/Payment.API/Data/DebtsContext.cs, DormService/Services/Payment/Payment.API/Data/IDebtsContext.cs, DormService/Services/Payment/Payment.API/Data/UserDebtsContextSeed.cs, DormService/Services/Payment/Payment.API/Entities/StudentDebts.cs, DormService/Services/Payment/Payment.API/Payment.API.csproj, DormService/Services/Payment/Payment.API/Program.cs, DormService/Services/Payment/Payment.API/Repository/DebtsRepository.cs, DormService/Services/Payment/Payment.API/Repository/IDebtsRepository.cs
Need to reimplement classes in Entities.
=> Create GET method for debts

DormService/Services/Laundry/Laundry.API/Controllers/WashingMachineController.cs, DormService/Services/Laundry/Laundry.API/Data/IWashingMachineContext.cs, DormService/Services/Laundry/Laundry.API/Data/LaundryDayGenerator.cs, DormService/Services/Laundry/Laundry.API/Data/WashingMachineContext.cs, DormService/Services/Laundry/Laundry.API/Entities/WashingMachine.cs, DormService/Services/Laundry/Laundry.API/Repository/IWashingMachineRepository.cs, DormService/Services/Laundry/Laundry.API/Repository/WashingMachineRepository.cs
=> Add implementation for fetching machines by date

DormService/Services/Payment/Payment.API/Controllers/DebtsController.cs, DormService/Services/Payment/Payment.API/Entities/StudentDebts.cs, DormService/Services/Payment/Payment.API/Repository/DebtsRepository.cs, DormService/Services/Payment/Payment.API/Repository/IDebtsRepository.cs
After the successful payment of a certain debt, the balance of that debt changes
=> Create put method for successful payment

DormService/Services/Payment/Payment.API/Controllers/DebtsController.cs, DormService/Services/Payment/Payment.API/Repository/DebtsRepository.cs, DormService/Services/Payment/Payment.API/Repository/IDebtsRepository.cs
Admin will be able to create new student with default(all zeros) or customized debts.
=> Implement POST method for new student

DormService/Services/Payment/Payment.API/Controllers/DebtsController.cs, DormService/Services/Payment/Payment.API/Repository/DebtsRepository.cs, DormService/Services/Payment/Payment.API/Repository/IDebtsRepository.cs
Admin will be able to delete a student by his studentID.
=> Implement DELETE method for deleting student

DormService/Services/Canteen/Canteen.API/UserMealsInfo/Controllers/UserMealsController.cs, DormService/Services/Canteen/Canteen.API/UserMealsInfo/Entities/UserMeals.cs, DormService/Services/Canteen/Canteen.API/UserMealsInfo/Repositories/UserMealsRepository.cs
On **GET** request, if there is no data in database for that student, create new `UserMeals`.
=> feat: Canteen - create new UserMeals

DormService/Services/Payment/Payment.API/Repository/DebtsRepository.cs, DormService/Services/Payment/Payment.API/Repository/IDebtsRepository.cs
During the first access,  student debts are initialized by default values
=> Update GET method for the case with new student

DormService/DormService.sln, DormService/Security/IdentiryServer/IdentiryServer.csproj, DormService/Security/IdentiryServer/IdentiryServer.http, DormService/Security/IdentiryServer/Program.cs, DormService/Security/IdentiryServer/appsettings.Development.json, DormService/Security/IdentiryServer/appsettings.json
- Added `IdentityServer`
- Installed necessary packages
=> feat: Security - Initialize security service

DormService/Services/Laundry/Laundry.API/Controllers/WashingMachineController.cs, DormService/Services/Laundry/Laundry.API/Repository/WashingMachinesReservations/IWashingMachineRepository.cs, DormService/Services/Laundry/Laundry.API/Repository/WashingMachinesReservations/WashingMachineRepository.cs
=> Add machine reservation

DormService/Services/Laundry/Laundry.API/Controllers/WashinhMachineManagementController.cs, DormService/Services/Laundry/Laundry.API/Repository/WashingMachinesManagement/IWashingMachineManagementRepository.cs, DormService/Services/Laundry/Laundry.API/Repository/WashingMachinesManagement/WashingMachineManagementRepository.cs
=> Add manageable machines fetch

DormService/Services/Laundry/Laundry.API/Controllers/WashinhMachineManagementController.cs, DormService/Services/Laundry/Laundry.API/Repository/WashingMachinesManagement/IWashingMachineManagementRepository.cs, DormService/Services/Laundry/Laundry.API/Repository/WashingMachinesManagement/WashingMachineManagementRepository.cs
=> Add managable machines delete

DormService/Services/Laundry/Laundry.API/Data/WashingMachinesReservations/LaundryDayGenerator.cs, DormService/Services/Laundry/Laundry.API/Entities/WashingMachine.cs, DormService/Services/Laundry/Laundry.API/Repository/WashingMachinesReservations/WashingMachineRepository.cs
=> Sync LaundryDayGenerator with available machines from the Laundry room

DormService/docker-compose.override.yml, DormService/docker-compose.yml
- Added `identitydb` to `docker-compose`
=> feat: Security - Add Docker support

DormService/DormService.sln, DormService/Services/Documentation/Documentation.API/Documentation.API/Controllers/DocumentationListController.cs, DormService/Services/Documentation/Documentation.API/Documentation.API/Documentation.API.csproj, DormService/Services/Documentation/Documentation.API/Documentation.API/Entities/Document.cs, DormService/Services/Documentation/Documentation.API/Documentation.API/Entities/DocumentationList.cs, DormService/Services/Documentation/Documentation.API/Documentation.API/Program.cs, DormService/Services/Documentation/Documentation.API/Documentation.API/appsettings.Development.json, DormService/Services/Documentation/Documentation.API/Documentation.API/appsettings.json
- Initialize documentation service
- Create sample model
- Create sample controller
=> Initialize documentation service

DormService/Services/Documentation/Documentation.API/Documentation.API/Data/DocumentContext.cs, DormService/Services/Documentation/Documentation.API/Documentation.API/Data/IDocumentContext.cs
Add Document MongoDB collection
=> feat: Add document collection

DormService/Services/Laundry/Laundry.API/Controllers/WashingMachineController.cs, DormService/Services/Laundry/Laundry.API/GrpcServices/PaymentGrpcService.cs, DormService/Services/Laundry/Laundry.API/Laundry.API.sln, DormService/Services/Laundry/Laundry.API/Laundry.csproj, DormService/Services/Laundry/Laundry.API/Program.cs, DormService/Services/Payment/Payment.GRPC/Dockerfile, DormService/Services/Payment/Payment.GRPC/Payment.GRPC.csproj, DormService/docker-compose.override.yml, DormService/docker-compose.yml
=> Add support for grpc communication with Payment service

DormService/Services/Laundry/Laundry.API/Controllers/WashingMachineController.cs, DormService/Services/Laundry/Laundry.API/Entities/WashingMachineConfiguration.cs, DormService/Services/Laundry/Laundry.API/Repository/WashingMachinesManagement/IWashingMachineManagementRepository.cs, DormService/Services/Laundry/Laundry.API/Repository/WashingMachinesManagement/WashingMachineManagementRepository.cs, DormService/docker-compose.override.yml
=> Implemet machine suggestions API call

DormService/Security/IdentiryServer/Data/ApplicationContext.cs, DormService/Security/IdentiryServer/Data/EntityTypeConfigurations/RoleConfiguration.cs, DormService/Security/IdentiryServer/Migrations/20240608164153_AddedRolesToDb.Designer.cs, DormService/Security/IdentiryServer/Migrations/20240608164153_AddedRolesToDb.cs, DormService/Security/IdentiryServer/appsettings.Development.json
- Add User roles
- Update database
=> feat: Security - Add User roles

DormService/Security/IdentiryServer/Controllers/AuthenticationController.cs, DormService/Security/IdentiryServer/Controllers/Base/RegistrationControllerBase.cs, DormService/Security/IdentiryServer/DTOs/NewUserDTO.cs, DormService/Security/IdentiryServer/Extensions/IdentityExtensions.cs, DormService/Security/IdentiryServer/IdentiryServer.csproj, DormService/Security/IdentiryServer/Mapper/IdentityProfile.cs, DormService/Security/IdentiryServer/Program.cs
- Add NewUserDto
- Add controller and base controller for user registration
Closes #106
=> feat: Security - User registration

DormService/Security/IdentityServer/Controllers/UserController.cs, DormService/Security/IdentityServer/DTOs/UserDetails.cs, DormService/Security/IdentityServer/Dockerfile, DormService/Security/IdentityServer/IdentityServer.csproj, DormService/Security/IdentityServer/Mapper/IdentityProfile.cs, DormService/docker-compose.override.yml, DormService/docker-compose.yml
Only users with Administrator role can use implemented endpoints:
- `GetAllUsers`
- `GetUser`
=> feat: Security - Implement get user info endpoint

DormService/Security/IdentityServer/Controllers/AuthenticationController.cs, DormService/Security/IdentityServer/Controllers/Base/RegistrationControllerBase.cs, DormService/Security/IdentityServer/DTOs/AuthenticationModel.cs, DormService/Security/IdentityServer/DTOs/RefreshTokenModel.cs, DormService/Security/IdentityServer/Data/ApplicationContext.cs, DormService/Security/IdentityServer/Data/UserConfiguration.cs, DormService/Security/IdentityServer/Entities/RefreshToken.cs, DormService/Security/IdentityServer/Entities/User.cs, DormService/Security/IdentityServer/Migrations/20240611194612_AddedRefreshTokensToUsers.Designer.cs, DormService/Security/IdentityServer/Migrations/20240611194612_AddedRefreshTokensToUsers.cs, DormService/Security/IdentityServer/Services/AuthenticationService.cs, DormService/Security/IdentityServer/Services/IAuthenticationService.cs, DormService/Security/IdentityServer/appsettings.Development.json
- Created new entities and DTOs 
- Implemented the necessary methods for refreshing the access token
- Added new endpoint
=> Implement refresh token

DormService/DormApps/dorm-spa/src/Apps/LaundryPage/LaudnryPage.tsx, DormService/DormApps/dorm-spa/src/components/Modals/ModalDialog.tsx, DormService/DormApps/dorm-spa/src/components/Modals/modal-dialog.scss, DormService/DormApps/dorm-spa/src/design/design-ui.scss, DormService/DormApps/dorm-spa/src/index.tsx
=> Add modals and test them on the laundry page

DormService/DormApps/dorm-spa/src/services/BaseService.ts
=> Add base service

DormService/Services/Documentation/Documentation.API/Documentation.API/Controllers/DocumentationListController.cs
=> fix: change paths

DormService/Services/Canteen/Canteen.API/Canteen.API.csproj, DormService/Services/Canteen/Canteen.API/OrderMealsInfo/Controllers/OrderMealsController.cs, DormService/Services/Canteen/Canteen.API/Program.cs, DormService/Services/Canteen/Canteen.API/UserMealsInfo/Controllers/UserMealsController.cs, DormService/Services/Canteen/Canteen.API/appsettings.Development.json
- Add service protection
- Validate username
=> feat: Canteen - Add service protection

DormService/Services/Payment/Payment.API/Controllers/DebtsController.cs, DormService/Services/Payment/Payment.API/Payment.API.csproj, DormService/Services/Payment/Payment.API/Program.cs, DormService/Services/Payment/Payment.API/appsettings.Development.json
Roles:
- Administrator
- Student
=> Add method protection in Payment service

DormService/Services/Laundry/Laundry.API/Controllers/WashingMachineController.cs, DormService/Services/Laundry/Laundry.API/Entities/DTOs/WashingMachineCofigurationDTO.cs, DormService/Services/Laundry/Laundry.API/Entities/DTOs/WashingMachineReservationDTO.cs, DormService/Services/Laundry/Laundry.API/Entities/WashingMachine.cs, DormService/Services/Laundry/Laundry.API/Entities/WashingMachineConfiguration.cs, DormService/Services/Laundry/Laundry.API/Program.cs, DormService/Services/Laundry/Laundry.API/Repository/WashingMachinesReservations/IWashingMachineRepository.cs, DormService/Services/Laundry/Laundry.API/Repository/WashingMachinesReservations/WashingMachineRepository.cs
=> Laundry service cleanup

DormService/Services/Documentation/Documentation.API/Documentation.API/Controllers/DocumentationListController.cs, DormService/Services/Documentation/Documentation.API/Documentation.API/Data/DocumentContext.cs, DormService/Services/Documentation/Documentation.API/Documentation.API/Documentation.API.csproj, DormService/Services/Documentation/Documentation.API/Documentation.API/Entities/Document.cs, DormService/Services/Documentation/Documentation.API/Documentation.API/Entities/DocumentationList.cs, DormService/Services/Documentation/Documentation.API/Documentation.API/Repositories/Interfaces/DocumentationListRepository.cs, DormService/Services/Documentation/Documentation.API/Documentation.API/Repositories/Interfaces/IDocumentationListRepository.cs, DormService/Services/Documentation/Documentation.API/Documentation.API/appsettings.json
Fix bug when deleting uploaded document.
Reformat code so the operations for documents based on their name are now in two separate functions (get and set). There is no need to check each document individually.
=> fix: fix bug in delete document endpoint and refactor code

DormService/Mailing/Models/Email.cs, DormService/Services/Documentation/Documentation.API/Documentation.API/Controllers/DocumentationListController.cs
Send email to user on successful document upload
=> feat: Send email on successfull document upload

DormService/DormApps/dorm-spa/src/Apps/PaymentPage/PaymentPage.tsx, DormService/DormApps/dorm-spa/src/Apps/PaymentPage/models/DebtsModel.ts, DormService/DormApps/dorm-spa/src/Apps/PaymentPage/payment-page.scss, DormService/DormApps/dorm-spa/src/Apps/PaymentPage/services/PaymentService.ts, DormService/DormApps/dorm-spa/src/services/BaseService.ts
* Pop up notifications
* Create student feature for Administrator
* Remove _id from StudentDebts model
* Set min constraint on Amount field
=> Set pop up notifications for all cases

DormService/Services/Payment/Payment.API/Controllers/DebtsController.cs, DormService/Services/Payment/Payment.Common/Entities/StudentDebts.cs, DormService/Services/Payment/Payment.Common/Repository/DebtsRepository.cs
* Edge cases covered
* Comment method protection
* Remove _id from StudentDebts
=> Cover all cases for every method in controller

DormService/DormApps/dorm-spa/src/Apps/PaymentPage/PaymentPage.tsx, DormService/DormApps/dorm-spa/src/Apps/PaymentPage/models/DebtsModel.ts, DormService/DormApps/dorm-spa/src/Apps/PaymentPage/payment-page.scss
* Confirmation dialog for paying
* Modify other methods
* Create const for default student debts
* Minor style change
=> Set confirmation dialog for paying

DormService/DormApps/dorm-spa/src/Apps/DocumentationPage/DocumentForm.tsx, DormService/DormApps/dorm-spa/src/Apps/DocumentationPage/DocumentationPage.tsx, DormService/DormApps/dorm-spa/src/Apps/DocumentationPage/DropDownMenu.tsx, DormService/DormApps/dorm-spa/src/Apps/DocumentationPage/GradeDegreeSelection.tsx, DormService/DormApps/dorm-spa/src/Apps/DocumentationPage/document-form.scss, DormService/DormApps/dorm-spa/src/Apps/DocumentationPage/document-page.scss, DormService/DormApps/dorm-spa/src/Apps/DocumentationPage/dropdown-menu.scss, DormService/DormApps/dorm-spa/src/Apps/DocumentationPage/services/DocumentationService.ts, DormService/DormApps/dorm-spa/src/design/design-ui.scss, DormService/Services/Documentation/Documentation.API/Documentation.API/Controllers/DocumentationListController.cs
Add logic for selecting which files should be uploaded based on grade and degree of studies
Also add option to calculate points for dorm application based on input values, grade and degree
Add style for Documentation page
=> feat: add logic and style for documentation page

DormService/Services/Payment/Payment.Common/Repository/DebtsRepository.cs
=> Cover one more edge case for reducing credit in gRPC communication

DormService/DormApps/dorm-spa/src/Apps/DocumentationPage/DocumentationPage.tsx
Limit values of input fields for calculating points
=> limit input values for point calculation
